### ISSUE TITLE
support for using other selectors such as class etc 

### ISSUE THREAD

**Issue by emahuni** [tinymins/vue-transfer-dom.js#2]
I think it'd be more powerful if it can additionally use if used with `{ target: "input.class-to-select" }` this can be implemented with `document.querySelector(target)` instead of `getElementById(target)`. The id will only be used if the target is specified as a part of the directive.

**Comment by tinymins** [comment]
That's a good idea, thanks! https://github.com/tinymins/vue-transfer-dom.js/commit/5907d1959a508635967e60357eab05fa770fabc5
