### ISSUE TITLE
Documentation need to have a bit more examples

### ISSUE THREAD

**Issue by emahuni** [tinymins/vue-transfer-dom.js#3]
The documentation is lacking some information and explanations as to how to implement it. It says name and instead it's using id or element. It also assumes that we get to what name refers to a-forehand.

**Comment by tinymins** [comment]
I've write some documentation just now, but I think my poor writing English may make some mistakes. So would you mind review and see if there is any problem or suggestion? https://github.com/tinymins/vue-transfer-dom.js/blob/master/README.md

**Comment by emahuni** [comment]
Ok let me check it out.
